// Virality Predictor — Higgsfield-style neuro-engagement model.
//
// This module produces a structured "virality strength" read-out for a video:
// an overall engagement score, hook strength, retention (sustain), and a set of
// simulated brain-region activations (Visual Cortex, Auditory Cortex, ...).
//
// The scores here are generated by a deterministic pseudo-neural model so the
// UI is fully interactive without a backend. The public shape
// (`predictVirality` -> `ViralityResult`) is intentionally the seam where a
// real inference API would be plugged in later.

export type RegionTone = "good" | "warning" | "danger";
export type ViralityTier = "low" | "medium" | "high";

export interface ViralityRegion {
  key: string;
  label: string;
  /** 0-100 activation. For most regions higher = better; see `higherIsBetter`. */
  value: number;
  tone: RegionTone;
  higherIsBetter: boolean;
  hint: string;
}

export interface ViralityResult {
  engagement: number; // 0-100 overall
  hookScore: number; // 0-100, first-3-seconds pull
  sustainPct: number; // 0-100 retention through the clip
  durationSec: number;
  tier: ViralityTier;
  regions: ViralityRegion[];
  verdict: string;
}

export interface ViralityInput {
  url: string;
  platform: string;
  caption?: string;
  /** Optional known duration in seconds; otherwise derived from the seed. */
  durationSec?: number;
}

/** Deterministic string hash -> 32-bit seed. */
function hashSeed(input: string): number {
  let h = 2166136261;
  for (let i = 0; i < input.length; i++) {
    h ^= input.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

/** mulberry32 PRNG — same seed always yields the same sequence. */
function makeRng(seed: number): () => number {
  let a = seed || 1;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const clamp = (n: number, lo = 0, hi = 100) => Math.max(lo, Math.min(hi, Math.round(n)));

function toneFor(value: number, higherIsBetter: boolean): RegionTone {
  const score = higherIsBetter ? value : 100 - value;
  if (score >= 60) return "good";
  if (score >= 40) return "warning";
  return "danger";
}

/**
 * Run the (simulated) virality analysis. Deterministic for a given input, so
 * re-analyzing the same video reproduces the same read-out.
 */
export function predictVirality(input: ViralityInput): ViralityResult {
  const seedStr = `${input.platform}::${input.url}::${input.caption ?? ""}`;
  const rng = makeRng(hashSeed(seedStr));
  const jitter = (base: number, spread: number) => base + (rng() - 0.5) * 2 * spread;

  const durationSec = input.durationSec ?? Math.round(8 + rng() * 45); // 8s–53s

  const visual = clamp(jitter(52, 22));
  const auditory = clamp(jitter(46, 20));
  const language = clamp(jitter(48, 22));
  const attention = clamp(jitter(55, 20));
  // Focus Drift: higher = worse retention. Longer clips drift more.
  const durationPenalty = Math.min(28, Math.max(0, (durationSec - 12) * 0.8));
  const focusDrift = clamp(jitter(44, 16) + durationPenalty);

  const hookScore = clamp(visual * 0.45 + attention * 0.4 + auditory * 0.15 - focusDrift * 0.15);
  const sustainPct = clamp(100 - focusDrift * (0.4 + rng() * 0.5));
  const engagement = clamp(
    hookScore * 0.34 +
      attention * 0.2 +
      visual * 0.16 +
      auditory * 0.12 +
      language * 0.12 +
      (100 - focusDrift) * 0.06,
  );

  const regions: ViralityRegion[] = [
    { key: "visual", label: "Visual Cortex", value: visual, higherIsBetter: true, tone: toneFor(visual, true), hint: "Força do estímulo visual e do scroll-stop." },
    { key: "auditory", label: "Auditory Cortex", value: auditory, higherIsBetter: true, tone: toneFor(auditory, true), hint: "Resposta a som, trilha e voz." },
    { key: "language", label: "Language Network", value: language, higherIsBetter: true, tone: toneFor(language, true), hint: "Clareza da mensagem e legendas." },
    { key: "attention", label: "Attention Control", value: attention, higherIsBetter: true, tone: toneFor(attention, true), hint: "Capacidade de segurar o foco." },
    { key: "focusDrift", label: "Focus Drift", value: focusDrift, higherIsBetter: false, tone: toneFor(focusDrift, false), hint: "Risco de desistência — quanto menor, melhor." },
  ];

  const tier: ViralityTier = engagement >= 66 ? "high" : engagement >= 40 ? "medium" : "low";

  const verdict = buildVerdict({ tier, engagement, hookScore, focusDrift, regions });

  return { engagement, hookScore, sustainPct, durationSec, tier, regions, verdict };
}

function buildVerdict(args: {
  tier: ViralityTier;
  engagement: number;
  hookScore: number;
  focusDrift: number;
  regions: ViralityRegion[];
}): string {
  const { tier, hookScore, focusDrift } = args;
  const weakest = [...args.regions]
    .filter((r) => r.higherIsBetter)
    .sort((a, b) => a.value - b.value)[0];

  const head =
    tier === "high"
      ? "Alto potencial de viralização."
      : tier === "medium"
        ? "Potencial mediano — dá pra escalar com ajustes."
        : "Potencial baixo no formato atual.";

  const hookNote =
    hookScore < 40
      ? " O gancho dos primeiros segundos está fraco: abra com o pico da ação ou uma pergunta."
      : hookScore < 60
        ? " O gancho segura, mas pode ser mais agressivo nos 3 primeiros segundos."
        : " Gancho forte — a abertura prende bem.";

  const driftNote =
    focusDrift >= 60
      ? " O Focus Drift está alto: corte o meio, acelere os cortes e reduza a duração."
      : focusDrift >= 45
        ? " Há alguma perda de foco no meio — encurte as pausas."
        : " A retenção se mantém estável até o fim.";

  const regionNote = weakest ? ` Reforce a região mais fraca: ${weakest.label}.` : "";

  return head + hookNote + driftNote + regionNote;
}
